ideALto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('web/', include('web.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('registrar/', views.registrar, name='registrar'),
    path('crearUsuario/', views.crearUsuario, name='crearUsuario'), 
]

web/models.py
from django.db import models
from django.contrib.auth.models import User
import random
import string
# Create your models here.

def generate_random_code(length=6):
    """Genera un código alfanumérico aleatorio de la longitud especificada."""
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))

class Vecino(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.RESTRICT)
    codigo_usuario = models.CharField(max_length=8, null=False, blank=False, unique=True)
    ci = models.CharField(max_length=10, null=False, blank=False)

    def save(self, *args, **kwargs):
        # Si el código_usuario está vacío (es decir, estamos creando un nuevo Vecino)
        if not self.codigo_usuario:
            # Genera un código aleatorio
            self.codigo_usuario = generate_random_code()
            # Asegúrate de que el código sea único
            while Vecino.objects.filter(codigo_usuario=self.codigo_usuario).exists():
                self.codigo_usuario = generate_random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.codigo_usuario

class Distrito(models.Model):
    nombre = models.CharField(max_length=50, null=False, blank=False)
    descripcion = models.TextField(null=True)

    def __str__(self):
        return self.nombre

class ZonaUrb(models.Model):
    nombre = models.CharField(max_length=80, null=False, blank=False)
    descripcion = models.TextField()
    ciudad = models.CharField(max_length=50, default='El alto')
    cordenadas = models.CharField(max_length=50, null=False, blank=False)
    distrito = models.ForeignKey(Distrito, on_delete=models.RESTRICT)

    def __str__(self):
        return self.nombre
    
class CalleAv(models.Model):
    nombre = models.CharField(max_length=100, null=False, blank=False)
    descripcion = models.TextField(null=True)
    numero_vivienda = models.IntegerField(null=False, blank=False)
    zona_urb = models.ForeignKey(ZonaUrb, on_delete=models.RESTRICT)

    def __str__(self):
        return self.nombre


class SolicitudVecino(models.Model):
    vecino = models.ForeignKey(Vecino, on_delete=models.RESTRICT)
    distrito = models.ForeignKey(Distrito, on_delete=models.RESTRICT)
    zona_urbanizacion = models.ForeignKey(ZonaUrb, on_delete=models.RESTRICT)
    fecha = models.DateField(auto_now_add=True)
    foto_solicitud = models.ImageField(upload_to='trabajo', blank=True)
    ubicacion_direccion = models.CharField(max_length=100, null=False, blank=False)
    latitud = models.FloatField(null=True, blank=True, default=-16.500000)
    longitud = models.FloatField(null=True, blank=True, default=-68.150000)
    celular = models.IntegerField()

    def __str__(self):
        return self.vecino.codigo_usuario
    
    def get_google_maps_url(self):
        if self.latitud and self.longitud:
            return f"https://www.google.com/maps?q={self.latitud},{self.longitud}"
        return None

class FichaOperativa(models.Model):

    ESTADO_OPCIONES = [
        ('pendiente', 'Pendiente'),
        ('en_progreso', 'En Progreso'),
        ('completado', 'Completado'),
        ('cancelado', 'Cancelado'),
    ]
        
    distrito = models.ForeignKey(Distrito, on_delete=models.RESTRICT)
    zonaurb = models.ForeignKey(ZonaUrb, on_delete=models.RESTRICT)
    codigo = models.ForeignKey(Vecino, on_delete=models.RESTRICT)
    latitud = models.FloatField(null=True, blank=True, default=-16.500000)
    longitud = models.FloatField(null=True, blank=True, default=-68.150000)
    fecha = models.DateField(auto_now_add=True)
    maquinaria = models.CharField(max_length=50, null=True, blank=True)
    tecnico_supervisor = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    volumen = models.CharField(max_length=100, null=True, blank=True)
    descripcion_trabajo = models.TextField(default='Descripcion...')
    foto_inicio = models.ImageField(upload_to='trabajo', blank=True)
    foto_desarollo = models.ImageField(upload_to='trabajo', blank=True)
    foto_culminado = models.ImageField(upload_to='trabajo', blank=True)
    estado = models.CharField(max_length=30, choices=ESTADO_OPCIONES, default='pendiente')

    def __Str__(self):
        return f'{self.codigo} - {self.get_estado_display()}'
    
class Solicitudes(models.Model):
    
    ESTADO_OPCIONES = [
        ('pendiente', 'Pendiente'),
        ('en_progreso', 'En Progreso'),
        ('completado', 'Completado'),
        ('cancelado', 'Cancelado'),
    ]

    solicitud_vecino = models.ForeignKey(SolicitudVecino, on_delete=models.RESTRICT)
    ficha_operativa = models.ForeignKey(FichaOperativa, null=True, blank=True, on_delete=models.SET_NULL)
    descripcion = models.TextField(null=True)
    estado = models.CharField(max_length=30, choices=ESTADO_OPCIONES, default='pendiente')

    def __str__(self):
        return f'{self.get_estado_display()}'

    def get_ficha_operativa_estado(self):
        if self.ficha_operativa:
            return self.ficha_operativa.estado
        return None

    def get_tecnico_supervisor(self):
        if self.ficha_operativa:
            return self.ficha_operativa.tecnico_supervisor
        return None

ideALto/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, 'index.html', {})

web/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Vecino, Distrito, ZonaUrb, CalleAv, SolicitudVecino, FichaOperativa, Solicitudes
from django.contrib.auth import login, logout, authenticate

# VISTAS PARA CLIENTES Y USUARIOS

def crearUsuario(request):
    if request.method == 'POST':
        dataUsuario = request.POST['name']
        dataPassword = request.POST['password']
        
        nuevoUsuario = User.objects.create_user(username=dataUsuario, password=dataPassword)
        
        if nuevoUsuario is not None:
            login(request, nuevoUsuario)
            return redirect('/web/registrar/')
            
    return render(request, 'usuario/login.html')
            
def registrar(request):
    return render(request, 'usuario/formulario.html', {})
    

templates/blog-detail.html
<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title> 404 Not Found
</title><style>@media (prefers-color-scheme:dark){body{background-color:#000!important}}</style></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">404</h1>
<h2 style="margin-top:20px;font-size: 30px;">Not Found
</h2>
<p>The resource requested could not be found on this server!</p>
</div></div></body></html>

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html>

<!-- Mirrored from demo.themeim.com/html/braine/contact.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 26 Jul 2024 17:54:25 GMT -->
<head>
	{% include "layouts/head.html" %}
</head>

<body>

<div class="page-wrapper">
	
	<!-- Preloader -->
	{% include "layouts/preloader.html" %}
	<!-- Preloader End -->
	
	<!-- Main Header -->
	<header class="main-header header-style-two alternate">
		{% include "layouts/header.html" %}
	</header>
	<!-- End Main Header -->
	
	<!-- Page Title -->
    <section class="page-title">
			<h2>Registrarse</h2>
			<ul class="bread-crumb clearfix">
				<li><a href="index.html">Inicio</a></li>
				<li>Registrarse</li>
			</ul>
        </div>
    </section>
    <!-- End Page Title -->

	<!-- Team Detail Form -->
	<section class="team-detail_form">
		<div class="auto-container">
			<div class="row clearfix">
				<!-- Column -->
				<div class="column col-lg-6 col-md-12 col-sm-12">
					<!-- Sec Title -->
					<div class="sec-title style-four">
						<div class="sec-title_title">Registro</div>
						<h2 class="sec-title_heading"><span>Unidad de Riesgo</span></h2>
						<div class="sec-title_text">Lorem ipsum dolor sit amet consectetur adipiscing <br> elit Ut et massa Aliquam in hendrerit urna.</div>
					</div>
					<!-- Social Box -->
					<div class="contact-social_box">
						<a href="https://facebook.com/"><i class="fa-brands fa-facebook-f"></i></a>
						<a href="https://twitter.com/"><i class="fa-brands fa-twitter"></i></a>
						<a href="https://youtube.com/"><i class="fa-brands fa-youtube"></i></a>
						<a href="https://instagram.com/"><i class="fa-brands fa-instagram"></i></a>
					</div>
				</div>
				<!-- Column -->
				<div class="column col-lg-6 col-md-12 col-sm-12">
					<div class="default-form contact-form">
						<form method="post" action="https://demo.themeim.com/html/braine/sendemail.php" id="contact-form">
							<div class="row clearfix">
								<!--Form Group-->
								<div class="form-group col-lg-6 col-md-6 col-sm-6">
									<input type="text" name="name" value="" placeholder="Name" required>
								</div>
								<!--Form Group-->
								<div class="form-group col-lg-6 col-md-6 col-sm-6">
									<input type="email" name="email" value="" placeholder="Email" required>
								</div>
								<div class="form-group col-lg-6 col-md-6 col-sm-6">
									<input type="text" name="phone" value="" placeholder="Phone" required>
								</div>
								<!--Form Group-->
								<div class="form-group col-lg-6 col-md-6 col-sm-6">
									<select name="country" class="custom-select-box">
										<option>Select service</option>
										<option>Service 01</option>
										<option>Service 02</option>
										<option>Service 03</option>
									</select>
								</div>
								<div class="col-lg-12 col-md-12 col-sm-12 form-group">
									<textarea class="" name="message" placeholder="Type comment here*"></textarea>
								</div>
								<div class="form-group col-lg-12 col-md-12 col-sm-12">
									<button type="button" class="template-btn btn-style-one">
										<span class="btn-wrap">
											<span class="text-one">Send now</span>
											<span class="text-two">Send now</span>
										</span>
									</button>
								</div>
								
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Team Detail Form -->

	<!-- Map One -->
	<section class="map-one">
		<div class="auto-container">
			<div class="map-one_map">
				<iframe width="820" height="560" id="gmap_canvas" src="https://maps.google.com/maps?q=636+5th+Ave%2C+New+York&amp;t=&amp;z=18&amp;ie=UTF8&amp;iwloc=&amp;output=embed"></iframe>
			</div>
		</div>
	</section>
	<!-- End Map One -->
	<!-- Main Footer -->
	<footer class="main-footer">
		{% include "layouts/footer.html" %}
	</footer>

</div>
<!-- End PageWrapper -->

{% load static %}

<div class="progress-wrap">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
</div>

<script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/appear.js' %}"></script>
<script src="{% static 'js/parallax.min.js' %}"></script>
<script src="{% static 'js/tilt.jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.paroller.min.js' %}"></script>
<script src="{% static 'js/wow.js' %}"></script>
<script src="{% static 'js/swiper.min.js' %}"></script>
<script src="{% static 'js/backtotop.js' %}"></script>
<script src="{% static 'js/odometer.js' %}"></script>
<script src="{% static 'js/parallax-scroll.js' %}"></script>

<script src="{% static 'js/gsap.min.js' %}"></script>
<script src="{% static 'js/SplitText.min.js' %}"></script>
<script src="{% static 'js/ScrollTrigger.min.js' %}"></script>
<script src="{% static 'js/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'js/ScrollSmoother.min.js' %}"></script>

<script src="{% static 'js/magnific-popup.min.js' %}"></script>
<script src="{% static 'js/nav-tool.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/element-in-view.js' %}"></script>
<script src="{% static 'js/validate.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>


<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->

</body>

<!-- Mirrored from demo.themeim.com/html/braine/contact.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 26 Jul 2024 17:54:26 GMT -->
</html>

templates/layouts/footer.html
{% load static %}
<div class="footer-bottom">
    <div class="auto-container">
        <div class="inner-container d-flex justify-content-between align-items-center flex-wrap">
            <div class="footer-logo"><a href="index.html"><img src="assets/images/logo.svg" alt="" title=""></a></div>
            <div class="footer-copyright">&copy; 2024 <a href="index.html">Luis Diaz</a>Todos los derechos reservados.</div>
            <!-- Social Box -->
            <div class="footer-social_box">
                <a href="https://facebook.com/"><i class="fa-brands fa-facebook-f"></i></a>
                <a href="https://twitter.com/"><i class="fa-brands fa-twitter"></i></a>
                <a href="https://youtube.com/"><i class="fa-brands fa-youtube"></i></a>
                <a href="https://instagram.com/"><i class="fa-brands fa-instagram"></i></a>
            </div>
        </div>
    </div>
</div>

templates/layouts/head.html
{% load static %}
<meta charset="utf-8">
<title>Unidad|Riesgo</title>
<!-- Stylesheets -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/meanmenu.min.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">

<link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,600;1,700&amp;display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">

<link rel="shortcut icon" href="{% static '/images/favicon.png' %}" type="image/x-icon">
<link rel="icon" href="{% static '/images/favicon.png' %}" type="image/x-icon">

<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

templates/layouts/header.html
{% load static %}
<div class="header-lower">
  <div class="auto-container">
    <div class="inner-container">
      <div class="d-flex justify-content-between align-items-center flex-wrap">
        <div class="logo-box">
          <div class="logo">
            {% block 'logo' %}<a href="{% url "index" %}"
              ><img src="{% static '/images/logo.png' %}" alt="" title=""
            /></a>{% endblock  %}
          </div>
        </div>

        <div class="nav-outer d-flex flex-wrap">
          <!-- Main Menu -->
          <nav class="main-menu navbar-expand-md">
            <div class="navbar-header">
              <!-- Toggle Button -->
              <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>

            <div
              class="navbar-collapse collapse clearfix"
              id="navbarSupportedContent"
            >
              <ul class="navigation clearfix">
                <li>
                  <a href="{% url "index" %}">Inicio</a>
                </li>
                <li><a href="#">Acerca de Nosotros</a></li>
                <li class="#">
                  <a href="#">Geoportal</a>
                  <ul>
                    <li><a href="#">Faq</a></li>
                    <li><a href="#">Price</a></li>
                    <li><a href="#">Testimonial</a></li>
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Register</a></li>
                    <li><a href="#">Forgot password</a></li>
                    <li class="dropdown">
                      <a href="#">Team</a>
                      <ul>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Team detail</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#">Servicios</a>
                  <ul>
                    <li><a href="services.html">Services</a></li>
                    <li><a href="service-detail.html">Services detail</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#">Blog</a>
                  <ul>
                    <li><a href="#">Blog grid</a></li>
                    <li><a href="#">Blog classic</a></li>
                    <li><a href="#">Blog detail</a></li>
                    <li><a href="#">Not found</a></li>
                  </ul>
                </li>
                <li><a href="#">Contactos</a></li>
              </ul>
            </div>
          </nav>
        </div>

        <!-- Main Menu End-->
        <div class="outer-box d-flex align-items-center flex-wrap">
          <!-- Language DropDown -->
          <div class="language-dropdown">
            <button
              class="btn dropdown-toggle"
              type="button"
              id="dropdownMenuButton1"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <span class="flag"
              /></span>
              <span class="fa-solid fa-angle-down fa-fw"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li>
                <a class="dropdown-item" href="#"
                  ><span class="flag"
                  /></span>
                  English</a
                >
              </li>
              <li>
                <a class="dropdown-item" href="#"
                  ><span class="flag"
                  /></span>
                  Español</a
                >
              </li>
            </ul>
          </div>

          <!-- Button Box -->
          <div class="main-header_buttons">
            <a href="{% url 'web:registrar' %}" class="template-btn btn-style-two">
              <span class="btn-wrap">
                <span class="text-one">Registrarse</span>
                <span class="text-two">Registrarse</span>
              </span>
            </a>
            <a href="{% url 'web:crearUsuario' %}" class="template-btn btn-style-one">
              <span class="btn-wrap">
                <span class="text-one">Ingresar</span>
                <span class="text-two">Ingresar</span>
              </span>
            </a>
          </div>

          <!-- Mobile Navigation Toggler -->
          <div class="mobile-nav-toggler">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="icon icon-tabler icon-tabler-menu-2"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M4 6l16 0" />
              <path d="M4 12l16 0" />
              <path d="M4 18l16 0" />
            </svg>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--End Header Lower-->

<!-- Mobile Menu  -->
<div class="mobile-menu">
  <div class="menu-backdrop"></div>
  <div class="close-btn">
    <span class="icon fa-solid fa-xmark fa-fw"></span>
  </div>

  <nav class="menu-box">
    <div class="nav-logo">
      <a href="index.html"
        ><img src="{% static '/images/logo.png' %}" alt="" title=""
      /></a>
    </div>
    <div class="menu-outer">
      <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
    </div>
  </nav>
</div>
<!-- End Mobile Menu -->

templates/layouts/preloader.html
<!-- Cursor -->
<div class="cursor"></div>
<div class="cursor-follower"></div>
<!-- Cursor End -->

<!-- Preloader -->
<div class="loader-wrap">
  <div class="preloader">
    <div class="preloader-close">x</div>
    <div id="handle-preloader" class="handle-preloader">
      <div class="animation-preloader">
        <div class="txt-loading">
          <span data-text-preloader="R" class="letters-loading">R</span>
          <span data-text-preloader="I" class="letters-loading">I</span>
          <span data-text-preloader="E" class="letters-loading">E</span>
          <span data-text-preloader="S" class="letters-loading">S</span>
          <span data-text-preloader="G" class="letters-loading">G</span>
          <span data-text-preloader="O" class="letters-loading">O</span>
          <span data-text-preloader="S" class="letters-loading">S</span>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Preloader End -->

templates/layouts/scripts.html
{% load static %}
<div class="progress-wrap">
	<svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
		<path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
	</svg>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/appear.js' %}"></script>
<script src="{% static 'js/parallax.min.js' %}"></script>
<script src="{% static 'js/tilt.jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.paroller.min.js' %}"></script>
<script src="{% static 'js/wow.js' %}"></script>
<script src="{% static 'js/swiper.min.js' %}"></script>
<script src="{% static 'js/backtotop.js' %}"></script>
<script src="{% static 'js/odometer.js' %}"></script>
<script src="{% static 'js/parallax-scroll.js' %}"></script>

<script src="{% static 'js/gsap.min.js' %}"></script>
<script src="{% static 'js/SplitText.min.js' %}"></script>
<script src="{% static 'js/ScrollTrigger.min.js' %}"></script>
<script src="{% static 'js/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'js/ScrollSmoother.min.js' %}"></script>

<script src="{% static 'js/touchspin.js' %}"></script>
<script src="{% static 'js/jquery.marquee.min.js' %}"></script>
<script src="{% static 'js/magnific-popup.min.js' %}"></script>
<script src="{% static 'js/nav-tool.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/element-in-view.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->

templates/service.html
<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title> 404 Not Found
</title><style>@media (prefers-color-scheme:dark){body{background-color:#000!important}}</style></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">404</h1>
<h2 style="margin-top:20px;font-size: 30px;">Not Found
</h2>
<p>The resource requested could not be found on this server!</p>
</div></div></body></html>

templates/usuario/login.html
{% load static %}
<!DOCTYPE html>
<html>

<!-- Mirrored from demo.themeim.com/html/braine/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 26 Jul 2024 17:54:08 GMT -->
<head>
	{% include "layouts/head.html" %}
</head>

<body>

<div class="page-wrapper">
	
	<!-- Cursor -->
	{% include "layouts/preloader.html" %}
	<!-- Preloader End -->
	
	<!-- Main Header -->
	<header class="main-header header-style-two alternate">
		{% include "layouts/header.html" %}
	</header>
	<!-- End Main Header -->
	
	<!-- Page Title -->
    <section class="page-title">
        <div class="auto-container">
			<h2>Inicio de sesión</h2>
			<ul class="bread-crumb clearfix">
				<li><a href="index.html">Inicio</a></li>
				<li>Inicio de sesión nuevo</li>
			</ul>
        </div>
    </section>
    <!-- End Page Title -->

	<!-- Register One -->
	<section class="register-one">
		<div class="auto-container">
			<div class="inner-container">
				<h3>Login</h3>

				<!-- Register Form -->
				<div class="register-form">
					<form method="post" action="{% url "web:crearUsuario" %}">
						{% csrf_token %}
						<div class="form-group">
							<label>Usuario:</label>
							<input type="text" name="name" placeholder="" required="">
						</div>

						<div class="form-group">
							<label>Contraseña*</label>
							<span class="icon fa-regular fa-eye fa-fw"></span>
							<input type="password" name="password" placeholder="" required="">
						</div>

						<div class="form-group">
							<div class="d-flex justify-content-between align-items-center flex-wrap">
								<div class="check-box">
									<input type="checkbox" name="remember-password" id="type-1"> 
									<label for="type-1">Recordar</label>
								</div>
								<a class="forgot-psw" href="#">Olvidaste tu contraseña?</a>
							</div>
						</div>
						
						<div class="form-group">
							<!-- Button Box -->
							<button type="submit" class="submit-btn btn-style-one">
								<span class="btn-wrap">
									<span class="text-one">Crear Usuario</span>
									<span class="text-two">Crear Usuario</span>
								</span>
							</button>
						</div>
						
						<div class="form-group">
							<div class="creat-account">No tienes cuenta? <a href="#">Crear una cuenta</a></div>
						</div>

					</form>
				</div>
				<!-- End Default Form -->

			</div>
		</div>
	</section>
	<!-- End Register One -->
	</br>
	</br>
	<!-- Main Footer -->
	<footer class="main-footer">
		{% include "layouts/footer.html" %}
	</footer>

</div>
<!-- End PageWrapper -->
	{% include "layouts/scripts.html" %}
</body>

<!-- Mirrored from demo.themeim.com/html/braine/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 26 Jul 2024 17:54:08 GMT -->
</html>